### ISSUE TITLE
T5 Tokenizer

### ISSUE THREAD

**Issue by rishaandesai** [madcato/huggingface-coreml#2]
Hey! Did you get T5 to work? Xcode is missing a bunch of linked dependencies, so I'm trying to export the model into an encoder and decoder, and use your T5Model code in another workspace. How would I use the model code without errors?

**Comment by danieltvela** [comment]
T5 tokenizer is really complex and very hard to translate to other languages like Swift. 

I used T5 model by using pretokenized inputs. 

If yuo have errors, write them here into a comment. Maybe I could help.

**Comment by rishaandesai** [comment]
Thanks for the response! 

What are some of the pretokenized inputs you've used? 
I haven't gotten any errors yet; I just wanted to know the feasability of writing a tokenizer for T5.

**Comment by danieltvela** [comment]
I don't have those tokens, but you can generate yourself with Huggingface AutoTokenizer.

You can also read the T5 Tokenizer class in Huggingface github repo. I did it, and I decided not to port it to Swift, because its to complex.

**Comment by rishaandesai** [comment]
Oh, ok! Thanks!
